version: '3'

services:
  minio:
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=${S3__ACCESS_KEY:-minio}
      - MINIO_ROOT_PASSWORD=${S3__SECRET_KEY:-minio123}
    image: quay.io/minio/minio:${MINIO_VERSION:-latest}
    command: server /data --console-address ':9001'

  batch:
    build:
      dockerfile: batch.Dockerfile
    environment:
      - NODE_ENV=development
      - S3__ENDPOINT=minio
      - S3__PORT=9000
      - S3__SSL=false
      - S3__ACCESS_KEY=${S3__ACCESS_KEY:-minio}
      - S3__SECRET_KEY=${S3__SECRET_KEY:-minio123}
    depends_on: 
    - minio
